netgenerate --rand \
-j=traffic_light \
-t=edge.typ.xml \
--default.type="two_lane" \
--no-turnarounds=true \
--rand.max-distance=1000 \
--rand.min-distance=200 \
--rand.min-angle=60 \
--rand.iterations=200 \
--rand.neighbor-dist1=0 \
--rand.neighbor-dist2=0 \
--rand.neighbor-dist3=1 \
--rand.neighbor-dist4=1 \
--rand.neighbor-dist5=0 \
--rand.neighbor-dist6=0 \
--rand.grid=true \
--rand.connectivity=0.99 \
--rand.num-tries=150 \
--output-file=rand.net.xml \
--random